# Generated by Django 4.2.7 on 2024-04-02 06:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Ratings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating_model',
            old_name='movie',
            new_name='movie_id',
        ),
        migrations.RenameField(
            model_name='rating_model',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='movie_model',
            name='release_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
