# Generated by Django 4.2.7 on 2024-04-02 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ratings', '0002_rename_movie_rating_model_movie_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_model',
            name='email',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
